name: Deploy ML Training Image

# on:
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    secrets:
      GCP_SA_KEY:
        required: true
  # workflow_call:
  #   secrets:
  #     GCP_SA_KEY:
  #       required: true


env:
  prod-gcp-project-id: web-app-304613
  staging-gcp-project-id: staging-cloud-web-app 
  ml-image-name: tf-gpu.2-11

jobs:
  deploy-staging:
    runs-on: [ubuntu-latest]
    name: Rename testing container in staging and push to staging
    
    timeout-minutes: 30
    
    steps:
    - name: Get Image Tag
      id: get-image-tag
      run: |
        echo "image-tag=$(date -u +'%Y-%m-%d')-dev-$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        
    - name: Deploy Model to Staging Test
      uses: viam-modules/classification-tflite/.github/actions/deploy@DATA-2821/workflows
      with:
        training-image-base-name: us-central1-docker.pkg.dev/${{env.staging-gcp-project-id}}/mltraining/${{env.ml-image-name}}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        gcp-project: ${{ env.staging-gcp-project-id }}
        image-tag: ${{ steps.get-image-tag.outputs.image-tag }}


