name: Deploy ML Training Image

# on:
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    secrets:
      GCP_SA_KEY:
        required: true
  # workflow_call:
  #   secrets:
  #     GCP_SA_KEY:
  #       required: true


env:
  prod-gcp-project-id: web-app-304613
  staging-gcp-project-id: staging-cloud-web-app 
  ml-image-name: tf-gpu.2-11

jobs:
  deploy-staging:
    runs-on: [ubuntu-latest]
    name: Rename testing container in staging and push to staging

    timeout-minutes: 30
    
    steps:
    - name: Deploy Model to Staging
      uses: viam-modules/classification-tflite/.github/workflows/actions/deploy
      with:
        training-image-base-name: us-central1-docker.pkg.dev/${{env.staging-gcp-project-id}}/mltraining/${{ env.ml-image-name}}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        gcp-project: ${{env.staging-gcp-project}}
  # deploy-to-prod:
  #   name: Deploy to Prod
  #   uses: viam-modules/classification-tflite/.github/workflows/actions/deploy@main
  #   with:
  #     training-image-base-name: us-central1-docker.pkg.dev/${{env.prod-gcp-project-id}}/mltraining/${{ env.ml-image-name}}
  #     GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  #     gcp-project: ${{env.staging-gcp-project}} 


