name: Deploy ML Training Image

# on:
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    secrets:
      GCP_SA_KEY:
        required: true
  # workflow_call:
  #   secrets:
  #     GCP_SA_KEY:
  #       required: true


env:
  prod-gcp-project-id: web-app-304613
  staging-gcp-project-id: staging-cloud-web-app 
  ml-image-name: tf-gpu.2-11

jobs:
  # image-tag:
  #   name: Get Image Tag
  #   runs-on: ubuntu-latest
  #   outputs:
  #     tag: ${{ steps.generate-tag.outputs.tag }}
  #     unique-id: ${{ steps.unique-id.unique-id }}
  #   steps:
  #     - id: generate-tag
  #       run: echo "tag=$(date -u +'%Y-%m-%d')-release-${{ github.sha }}" >> "${GITHUB_OUTPUT}"
  #     - id: unique-id
  #       run: echo "unique-id=$(date +'%Y-%d-%m-%H-%M-%s')" >> $GITHUB_OUTPUT
    
  # build-test-ml-container:
  #   name: Build training container for new Python scripts
  #   uses: 'viam-modules/classification-tflite/.github/workflows/build-test-ml-container.yml@main'
  #   with:
  #     image-tag: ${{ jobs.image-tag.outputs.tag }}
  #     gcp-project-id: ${{ env.staging-gcp-project-id }}
  #     service-account: app-service@staging-cloud-web-app.iam.gserviceaccount.com
  #     container-name-suffix: ${{ jobs.image-tag.outputs.unique-id }}
  #     training-image-name: us-central1-docker.pkg.dev/${{env.staging-gcp-project-id}}/mltraining/${{env.ml-image-name}}/${{ jobs.image-tag.outputs.tag }}
  #   secrets:
  #     GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  deploy-staging:
    runs-on: [ubuntu-latest]
    name: Rename testing container in staging and push to staging
    
    timeout-minutes: 30
        
    - name: Deploy Model to Staging Test
      uses: viam-modules/classification-tflite/.github/actions/deploy@DATA-2821/workflows
      with:
        training-image-base-name: us-central1-docker.pkg.dev/${{env.staging-gcp-project-id}}/mltraining/${{env.ml-image-name}}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        gcp-project: ${{ env.staging-gcp-project-id }}
        image-tag: ${{ steps.get-image-tag.outputs.image-tag }}


