name: Pull Request Update

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Lint
      run: poetry run black . --check
    - name: Test Docker Build
      run: docker build -f Dockerfile -t temp
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
      
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
      
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ vars.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
      
  #     - name: Build and export to Docker
  #       uses: docker/build-push-action@v6
  #       with:
  #         load: true
  #         tags: ${{ env.TEST_TAG }}
      
  #     - name: Test
  #       run: |
  #         docker run --rm ${{ env.TEST_TAG }}  
    # - name: Build Docker
    #   uses: viam-modules/classification-tflite/.github/actions/build_docker_image@DATA-2821/workflows

